// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifact.sql

package sqlc_queries

import (
	"context"
	"time"
)

const countArtifacts = `-- name: CountArtifacts :one
SELECT count(*)
FROM chat_message AS message
JOIN chat_session AS session ON session.uuid = message.chat_session_uuid
CROSS JOIN LATERAL jsonb_array_elements(message.artifacts) AS artifact(value)
WHERE message.user_id = $1
  AND message.is_deleted = false
  AND session.active = true
  AND ($2::text = '' OR concat_ws(' ', artifact.value->>'title', artifact.value->>'content', artifact.value->>'type', artifact.value->>'language', session.topic) ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR artifact.value->>'type' = $3::text)
  AND ($4::text = '' OR artifact.value->>'language' = $4::text)
  AND ($5::text = '' OR session.uuid = $5::text)
`

type CountArtifactsParams struct {
	UserID       int32  `json:"userId"`
	Search       string `json:"search"`
	ArtifactType string `json:"artifactType"`
	Language     string `json:"language"`
	SessionUuid  string `json:"sessionUuid"`
}

func (q *Queries) CountArtifacts(ctx context.Context, arg CountArtifactsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArtifacts,
		arg.UserID,
		arg.Search,
		arg.ArtifactType,
		arg.Language,
		arg.SessionUuid,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteArtifact = `-- name: DeleteArtifact :one
UPDATE chat_message AS message
SET artifacts = COALESCE((
    SELECT jsonb_agg(artifact.value ORDER BY artifact.ordinality)
    FROM jsonb_array_elements(message.artifacts) WITH ORDINALITY AS artifact(value, ordinality)
    WHERE artifact.value->>'uuid' <> $1::text
), '[]'::jsonb), updated_at = now()
WHERE message.user_id = $2
  AND message.is_deleted = false
  AND EXISTS (SELECT 1 FROM jsonb_array_elements(message.artifacts) AS artifact WHERE artifact->>'uuid' = $1::text)
RETURNING message.uuid
`

type DeleteArtifactParams struct {
	ArtifactUuid string `json:"artifactUuid"`
	UserID       int32  `json:"userId"`
}

func (q *Queries) DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteArtifact, arg.ArtifactUuid, arg.UserID)
	var uuid string
	err := row.Scan(&uuid)
	return uuid, err
}

const duplicateArtifact = `-- name: DuplicateArtifact :one
UPDATE chat_message AS message
SET artifacts = message.artifacts || (
    SELECT (artifact || jsonb_build_object('uuid', $1::text, 'title', artifact->>'title' || ' (Copy)'))
    FROM jsonb_array_elements(message.artifacts) AS artifact
    WHERE artifact->>'uuid' = $2::text
    LIMIT 1
), updated_at = now()
WHERE message.user_id = $3
  AND message.is_deleted = false
  AND EXISTS (SELECT 1 FROM jsonb_array_elements(message.artifacts) AS artifact WHERE artifact->>'uuid' = $2::text)
RETURNING message.uuid
`

type DuplicateArtifactParams struct {
	NewUuid      string `json:"newUuid"`
	ArtifactUuid string `json:"artifactUuid"`
	UserID       int32  `json:"userId"`
}

func (q *Queries) DuplicateArtifact(ctx context.Context, arg DuplicateArtifactParams) (string, error) {
	row := q.db.QueryRowContext(ctx, duplicateArtifact, arg.NewUuid, arg.ArtifactUuid, arg.UserID)
	var uuid string
	err := row.Scan(&uuid)
	return uuid, err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT
    CAST(artifact.value AS text) AS artifact_json,
    message.uuid AS message_uuid,
    session.uuid AS session_uuid,
    session.topic AS session_title,
    message.created_at,
    message.updated_at
FROM chat_message AS message
JOIN chat_session AS session ON session.uuid = message.chat_session_uuid
CROSS JOIN LATERAL jsonb_array_elements(message.artifacts) AS artifact(value)
WHERE message.user_id = $1
  AND message.is_deleted = false
  AND session.active = true
  AND ($2::text = '' OR concat_ws(' ', artifact.value->>'title', artifact.value->>'content', artifact.value->>'type', artifact.value->>'language', session.topic) ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR artifact.value->>'type' = $3::text)
  AND ($4::text = '' OR artifact.value->>'language' = $4::text)
  AND ($5::text = '' OR session.uuid = $5::text)
ORDER BY message.created_at DESC, artifact.value->>'uuid'
LIMIT $7 OFFSET $6
`

type ListArtifactsParams struct {
	UserID       int32  `json:"userId"`
	Search       string `json:"search"`
	ArtifactType string `json:"artifactType"`
	Language     string `json:"language"`
	SessionUuid  string `json:"sessionUuid"`
	PageOffset   int32  `json:"pageOffset"`
	PageLimit    int32  `json:"pageLimit"`
}

type ListArtifactsRow struct {
	ArtifactJson string    `json:"artifactJson"`
	MessageUuid  string    `json:"messageUuid"`
	SessionUuid  string    `json:"sessionUuid"`
	SessionTitle string    `json:"sessionTitle"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]ListArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifacts,
		arg.UserID,
		arg.Search,
		arg.ArtifactType,
		arg.Language,
		arg.SessionUuid,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtifactsRow
	for rows.Next() {
		var i ListArtifactsRow
		if err := rows.Scan(
			&i.ArtifactJson,
			&i.MessageUuid,
			&i.SessionUuid,
			&i.SessionTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifact = `-- name: UpdateArtifact :one
UPDATE chat_message AS message
SET artifacts = (
    SELECT jsonb_agg(
        CASE WHEN artifact.value->>'uuid' = $1::text
            THEN artifact.value || jsonb_build_object('title', $2::text, 'content', $3::text, 'language', $4::text)
            ELSE artifact.value
        END ORDER BY artifact.ordinality
    )
    FROM jsonb_array_elements(message.artifacts) WITH ORDINALITY AS artifact(value, ordinality)
), updated_at = now()
WHERE message.user_id = $5
  AND message.is_deleted = false
  AND EXISTS (SELECT 1 FROM jsonb_array_elements(message.artifacts) AS artifact WHERE artifact->>'uuid' = $1::text)
RETURNING message.uuid
`

type UpdateArtifactParams struct {
	ArtifactUuid string `json:"artifactUuid"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Language     string `json:"language"`
	UserID       int32  `json:"userId"`
}

func (q *Queries) UpdateArtifact(ctx context.Context, arg UpdateArtifactParams) (string, error) {
	row := q.db.QueryRowContext(ctx, updateArtifact,
		arg.ArtifactUuid,
		arg.Title,
		arg.Content,
		arg.Language,
		arg.UserID,
	)
	var uuid string
	err := row.Scan(&uuid)
	return uuid, err
}
