// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_user.sql

package sqlc_queries

import (
	"context"
	"time"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO auth_user (email, "password", first_name, last_name, username, is_staff, is_superuser)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined
`

type CreateAuthUserParams struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Username    string `json:"username"`
	IsStaff     bool   `json:"isStaff"`
	IsSuperuser bool   `json:"isSuperuser"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, createAuthUser,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.IsStaff,
		arg.IsSuperuser,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.LastLogin,
		&i.IsSuperuser,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.IsStaff,
		&i.IsActive,
		&i.DateJoined,
	)
	return i, err
}

const deleteAuthUser = `-- name: DeleteAuthUser :exec
DELETE FROM auth_user WHERE email = $1
`

func (q *Queries) DeleteAuthUser(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthUser, email)
	return err
}

const getAllAuthUsers = `-- name: GetAllAuthUsers :many
SELECT id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined FROM auth_user ORDER BY id
`

func (q *Queries) GetAllAuthUsers(ctx context.Context) ([]AuthUser, error) {
	rows, err := q.db.QueryContext(ctx, getAllAuthUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Password,
			&i.LastLogin,
			&i.IsSuperuser,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.IsStaff,
			&i.IsActive,
			&i.DateJoined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
SELECT id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined FROM auth_user WHERE email = $1
`

func (q *Queries) GetAuthUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getAuthUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.LastLogin,
		&i.IsSuperuser,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.IsStaff,
		&i.IsActive,
		&i.DateJoined,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined FROM auth_user WHERE id = $1
`

func (q *Queries) GetAuthUserByID(ctx context.Context, id int32) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getAuthUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.LastLogin,
		&i.IsSuperuser,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.IsStaff,
		&i.IsActive,
		&i.DateJoined,
	)
	return i, err
}

const getTotalActiveUserCount = `-- name: GetTotalActiveUserCount :one
SELECT COUNT(*) FROM auth_user WHERE is_active = true
`

func (q *Queries) GetTotalActiveUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalActiveUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserAnalysisByEmail = `-- name: GetUserAnalysisByEmail :one
SELECT 
    auth_user.first_name,
    auth_user.last_name,
    auth_user.email AS user_email,
    COALESCE(user_stats.total_messages, 0) AS total_messages,
    COALESCE(user_stats.total_token_count, 0) AS total_tokens,
    COALESCE(user_stats.total_sessions, 0) AS total_sessions,
    COALESCE(user_stats.total_messages_3_days, 0) AS messages_3_days,
    COALESCE(user_stats.total_token_count_3_days, 0) AS tokens_3_days,
    COALESCE(auth_user_management.rate_limit, $2::INTEGER) AS rate_limit
FROM auth_user
LEFT JOIN (
    SELECT 
        stats.user_id, 
        SUM(stats.total_messages) AS total_messages, 
        SUM(stats.total_token_count) AS total_token_count,
        COUNT(DISTINCT stats.chat_session_uuid) AS total_sessions,
        SUM(CASE WHEN stats.created_at >= NOW() - INTERVAL '3 days' THEN stats.total_messages ELSE 0 END) AS total_messages_3_days,
        SUM(CASE WHEN stats.created_at >= NOW() - INTERVAL '3 days' THEN stats.total_token_count ELSE 0 END) AS total_token_count_3_days
    FROM (
        SELECT user_id, chat_session_uuid, COUNT(*) AS total_messages, SUM(token_count) as total_token_count, MAX(created_at) AS created_at
        FROM chat_message
        WHERE is_deleted = false
        GROUP BY user_id, chat_session_uuid
    ) AS stats
    GROUP BY stats.user_id
) AS user_stats ON auth_user.id = user_stats.user_id
LEFT JOIN auth_user_management ON auth_user.id = auth_user_management.user_id
WHERE auth_user.email = $1
`

type GetUserAnalysisByEmailParams struct {
	Email            string `json:"email"`
	DefaultRateLimit int32  `json:"defaultRateLimit"`
}

type GetUserAnalysisByEmailRow struct {
	FirstName     string `json:"firstName"`
	LastName      string `json:"lastName"`
	UserEmail     string `json:"userEmail"`
	TotalMessages int64  `json:"totalMessages"`
	TotalTokens   int64  `json:"totalTokens"`
	TotalSessions int64  `json:"totalSessions"`
	Messages3Days int64  `json:"messages3Days"`
	Tokens3Days   int64  `json:"tokens3Days"`
	RateLimit     int32  `json:"rateLimit"`
}

func (q *Queries) GetUserAnalysisByEmail(ctx context.Context, arg GetUserAnalysisByEmailParams) (GetUserAnalysisByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAnalysisByEmail, arg.Email, arg.DefaultRateLimit)
	var i GetUserAnalysisByEmailRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.UserEmail,
		&i.TotalMessages,
		&i.TotalTokens,
		&i.TotalSessions,
		&i.Messages3Days,
		&i.Tokens3Days,
		&i.RateLimit,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined FROM auth_user WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.LastLogin,
		&i.IsSuperuser,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.IsStaff,
		&i.IsActive,
		&i.DateJoined,
	)
	return i, err
}

const getUserModelUsageByEmail = `-- name: GetUserModelUsageByEmail :many
SELECT 
    COALESCE(cm.model, 'unknown') AS model,
    COUNT(*) AS message_count,
    COALESCE(SUM(cm.token_count), 0) AS token_count,
    MAX(cm.created_at)::timestamp AS last_used
FROM chat_message cm
INNER JOIN auth_user au ON cm.user_id = au.id
WHERE au.email = $1 
    AND cm.is_deleted = false 
    AND cm.role = 'assistant'
    AND cm.model IS NOT NULL 
    AND cm.model != ''
GROUP BY cm.model
ORDER BY message_count DESC
`

type GetUserModelUsageByEmailRow struct {
	Model        string      `json:"model"`
	MessageCount int64       `json:"messageCount"`
	TokenCount   interface{} `json:"tokenCount"`
	LastUsed     time.Time   `json:"lastUsed"`
}

func (q *Queries) GetUserModelUsageByEmail(ctx context.Context, email string) ([]GetUserModelUsageByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserModelUsageByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserModelUsageByEmailRow
	for rows.Next() {
		var i GetUserModelUsageByEmailRow
		if err := rows.Scan(
			&i.Model,
			&i.MessageCount,
			&i.TokenCount,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecentActivityByEmail = `-- name: GetUserRecentActivityByEmail :many
SELECT 
    DATE(cm.created_at) AS activity_date,
    COUNT(*) AS messages,
    COALESCE(SUM(cm.token_count), 0) AS tokens,
    COUNT(DISTINCT cm.chat_session_uuid) AS sessions
FROM chat_message cm
INNER JOIN auth_user au ON cm.user_id = au.id
WHERE au.email = $1 
    AND cm.is_deleted = false 
    AND cm.created_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE(cm.created_at)
ORDER BY activity_date DESC
LIMIT 30
`

type GetUserRecentActivityByEmailRow struct {
	ActivityDate time.Time   `json:"activityDate"`
	Messages     int64       `json:"messages"`
	Tokens       interface{} `json:"tokens"`
	Sessions     int64       `json:"sessions"`
}

func (q *Queries) GetUserRecentActivityByEmail(ctx context.Context, email string) ([]GetUserRecentActivityByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRecentActivityByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecentActivityByEmailRow
	for rows.Next() {
		var i GetUserRecentActivityByEmailRow
		if err := rows.Scan(
			&i.ActivityDate,
			&i.Messages,
			&i.Tokens,
			&i.Sessions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessionHistoryByEmail = `-- name: GetUserSessionHistoryByEmail :many
SELECT 
    cs.uuid AS session_id,
    cs.model,
    COALESCE(COUNT(cm.id), 0) AS message_count,
    COALESCE(SUM(cm.token_count), 0) AS token_count,
    COALESCE(MIN(cm.created_at), cs.created_at)::timestamp AS created_at,
    COALESCE(MAX(cm.created_at), cs.updated_at)::timestamp AS updated_at
FROM chat_session cs
INNER JOIN auth_user au ON cs.user_id = au.id
LEFT JOIN chat_message cm ON cs.uuid = cm.chat_session_uuid AND cm.is_deleted = false
WHERE au.email = $1 AND cs.active = true
GROUP BY cs.uuid, cs.model, cs.created_at, cs.updated_at
ORDER BY cs.updated_at DESC
LIMIT $2 OFFSET $3
`

type GetUserSessionHistoryByEmailParams struct {
	Email  string `json:"email"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetUserSessionHistoryByEmailRow struct {
	SessionID    string      `json:"sessionId"`
	Model        string      `json:"model"`
	MessageCount interface{} `json:"messageCount"`
	TokenCount   interface{} `json:"tokenCount"`
	CreatedAt    time.Time   `json:"createdAt"`
	UpdatedAt    time.Time   `json:"updatedAt"`
}

func (q *Queries) GetUserSessionHistoryByEmail(ctx context.Context, arg GetUserSessionHistoryByEmailParams) ([]GetUserSessionHistoryByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserSessionHistoryByEmail, arg.Email, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSessionHistoryByEmailRow
	for rows.Next() {
		var i GetUserSessionHistoryByEmailRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Model,
			&i.MessageCount,
			&i.TokenCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessionHistoryCountByEmail = `-- name: GetUserSessionHistoryCountByEmail :one
SELECT COUNT(DISTINCT cs.uuid) AS total_sessions
FROM chat_session cs
INNER JOIN auth_user au ON cs.user_id = au.id
WHERE au.email = $1 AND cs.active = true
`

func (q *Queries) GetUserSessionHistoryCountByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserSessionHistoryCountByEmail, email)
	var total_sessions int64
	err := row.Scan(&total_sessions)
	return total_sessions, err
}

const getUserStats = `-- name: GetUserStats :many
SELECT 
    auth_user.first_name,
    auth_user.last_name,
    auth_user.email AS user_email,
    COALESCE(user_stats.total_messages, 0) AS total_chat_messages,
    COALESCE(user_stats.total_token_count, 0) AS total_token_count,
    COALESCE(user_stats.total_messages_3_days, 0) AS total_chat_messages_3_days,
    COALESCE(user_stats.total_token_count_3_days, 0) AS total_token_count_3_days,
    COALESCE(auth_user_management.rate_limit, $3::INTEGER) AS rate_limit
FROM auth_user
LEFT JOIN (
    SELECT chat_message_stats.user_id, 
           SUM(total_messages) AS total_messages, 
           SUM(total_token_count) AS total_token_count,
           SUM(CASE WHEN created_at >= NOW() - INTERVAL '3 days' THEN total_messages ELSE 0 END) AS total_messages_3_days,
           SUM(CASE WHEN created_at >= NOW() - INTERVAL '3 days' THEN total_token_count ELSE 0 END) AS total_token_count_3_days
    FROM (
        SELECT user_id, COUNT(*) AS total_messages, SUM(token_count) as total_token_count, MAX(created_at) AS created_at
        FROM chat_message
        GROUP BY user_id, chat_session_uuid
    ) AS chat_message_stats
    GROUP BY chat_message_stats.user_id
) AS user_stats ON auth_user.id = user_stats.user_id
LEFT JOIN auth_user_management ON auth_user.id = auth_user_management.user_id
ORDER BY total_chat_messages DESC, auth_user.id DESC
OFFSET $2
LIMIT $1
`

type GetUserStatsParams struct {
	Limit            int32 `json:"limit"`
	Offset           int32 `json:"offset"`
	DefaultRateLimit int32 `json:"defaultRateLimit"`
}

type GetUserStatsRow struct {
	FirstName              string `json:"firstName"`
	LastName               string `json:"lastName"`
	UserEmail              string `json:"userEmail"`
	TotalChatMessages      int64  `json:"totalChatMessages"`
	TotalTokenCount        int64  `json:"totalTokenCount"`
	TotalChatMessages3Days int64  `json:"totalChatMessages3Days"`
	TotalTokenCount3Days   int64  `json:"totalTokenCount3Days"`
	RateLimit              int32  `json:"rateLimit"`
}

func (q *Queries) GetUserStats(ctx context.Context, arg GetUserStatsParams) ([]GetUserStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserStats, arg.Limit, arg.Offset, arg.DefaultRateLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserStatsRow
	for rows.Next() {
		var i GetUserStatsRow
		if err := rows.Scan(
			&i.FirstName,
			&i.LastName,
			&i.UserEmail,
			&i.TotalChatMessages,
			&i.TotalTokenCount,
			&i.TotalChatMessages3Days,
			&i.TotalTokenCount3Days,
			&i.RateLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthUsers = `-- name: ListAuthUsers :many
SELECT id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined FROM auth_user ORDER BY id LIMIT $1 OFFSET $2
`

type ListAuthUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuthUsers(ctx context.Context, arg ListAuthUsersParams) ([]AuthUser, error) {
	rows, err := q.db.QueryContext(ctx, listAuthUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Password,
			&i.LastLogin,
			&i.IsSuperuser,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.IsStaff,
			&i.IsActive,
			&i.DateJoined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthUser = `-- name: UpdateAuthUser :one
UPDATE auth_user SET first_name = $2, last_name= $3, last_login = now() 
WHERE id = $1
RETURNING first_name, last_name, email
`

type UpdateAuthUserParams struct {
	ID        int32  `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type UpdateAuthUserRow struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

func (q *Queries) UpdateAuthUser(ctx context.Context, arg UpdateAuthUserParams) (UpdateAuthUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateAuthUser, arg.ID, arg.FirstName, arg.LastName)
	var i UpdateAuthUserRow
	err := row.Scan(&i.FirstName, &i.LastName, &i.Email)
	return i, err
}

const updateAuthUserByEmail = `-- name: UpdateAuthUserByEmail :one
UPDATE auth_user SET first_name = $2, last_name= $3, last_login = now() 
WHERE email = $1
RETURNING first_name, last_name, email
`

type UpdateAuthUserByEmailParams struct {
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type UpdateAuthUserByEmailRow struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

func (q *Queries) UpdateAuthUserByEmail(ctx context.Context, arg UpdateAuthUserByEmailParams) (UpdateAuthUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, updateAuthUserByEmail, arg.Email, arg.FirstName, arg.LastName)
	var i UpdateAuthUserByEmailRow
	err := row.Scan(&i.FirstName, &i.LastName, &i.Email)
	return i, err
}

const updateAuthUserRateLimitByEmail = `-- name: UpdateAuthUserRateLimitByEmail :one
INSERT INTO auth_user_management (user_id, rate_limit, created_at, updated_at)
VALUES ((SELECT id FROM auth_user WHERE email = $1), $2, NOW(), NOW())
ON CONFLICT (user_id) DO UPDATE SET rate_limit = $2, updated_at = NOW()
RETURNING rate_limit
`

type UpdateAuthUserRateLimitByEmailParams struct {
	Email     string `json:"email"`
	RateLimit int32  `json:"rateLimit"`
}

func (q *Queries) UpdateAuthUserRateLimitByEmail(ctx context.Context, arg UpdateAuthUserRateLimitByEmailParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateAuthUserRateLimitByEmail, arg.Email, arg.RateLimit)
	var rate_limit int32
	err := row.Scan(&rate_limit)
	return rate_limit, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE auth_user SET "password" = $2 WHERE email = $1
`

type UpdateUserPasswordParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Email, arg.Password)
	return err
}
