// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: chat_file.sql

package sqlc_queries

import (
	"context"
)

const createChatFile = `-- name: CreateChatFile :one
INSERT INTO chat_file (name, data, user_id, chat_session_uuid)
VALUES ($1, $2, $3, $4)
RETURNING id, name, data, created_at, user_id, chat_session_uuid
`

type CreateChatFileParams struct {
	Name            string `json:"name"`
	Data            []byte `json:"data"`
	UserID          int32  `json:"userID"`
	ChatSessionUuid string `json:"chatSessionUuid"`
}

func (q *Queries) CreateChatFile(ctx context.Context, arg CreateChatFileParams) (ChatFile, error) {
	row := q.db.QueryRowContext(ctx, createChatFile,
		arg.Name,
		arg.Data,
		arg.UserID,
		arg.ChatSessionUuid,
	)
	var i ChatFile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.UserID,
		&i.ChatSessionUuid,
	)
	return i, err
}

const deleteChatFile = `-- name: DeleteChatFile :one
DELETE FROM chat_file
WHERE id = $1
RETURNING id, name, data, created_at, user_id, chat_session_uuid
`

func (q *Queries) DeleteChatFile(ctx context.Context, id int32) (ChatFile, error) {
	row := q.db.QueryRowContext(ctx, deleteChatFile, id)
	var i ChatFile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.UserID,
		&i.ChatSessionUuid,
	)
	return i, err
}

const listChatFiles = `-- name: ListChatFiles :many
SELECT id, name, data, created_at, user_id, chat_session_uuid
FROM chat_file
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListChatFilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListChatFiles(ctx context.Context, arg ListChatFilesParams) ([]ChatFile, error) {
	rows, err := q.db.QueryContext(ctx, listChatFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatFile
	for rows.Next() {
		var i ChatFile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Data,
			&i.CreatedAt,
			&i.UserID,
			&i.ChatSessionUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
