// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: chat_logs.sql

package sqlc_queries

import (
	"context"
	"encoding/json"
)

const chatLogByID = `-- name: ChatLogByID :one
SELECT id, session, question, answer FROM chat_logs WHERE id = $1
`

func (q *Queries) ChatLogByID(ctx context.Context, id int32) (ChatLog, error) {
	row := q.db.QueryRowContext(ctx, chatLogByID, id)
	var i ChatLog
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.Question,
		&i.Answer,
	)
	return i, err
}

const createChatLog = `-- name: CreateChatLog :one
INSERT INTO chat_logs (session, question, answer)
VALUES ($1, $2, $3)
RETURNING id, session, question, answer
`

type CreateChatLogParams struct {
	Session  json.RawMessage
	Question json.RawMessage
	Answer   json.RawMessage
}

func (q *Queries) CreateChatLog(ctx context.Context, arg CreateChatLogParams) (ChatLog, error) {
	row := q.db.QueryRowContext(ctx, createChatLog, arg.Session, arg.Question, arg.Answer)
	var i ChatLog
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.Question,
		&i.Answer,
	)
	return i, err
}

const deleteChatLog = `-- name: DeleteChatLog :exec
DELETE FROM chat_logs WHERE id = $1
`

func (q *Queries) DeleteChatLog(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteChatLog, id)
	return err
}

const listChatLogs = `-- name: ListChatLogs :many
SELECT id, session, question, answer FROM chat_logs ORDER BY id
`

func (q *Queries) ListChatLogs(ctx context.Context) ([]ChatLog, error) {
	rows, err := q.db.QueryContext(ctx, listChatLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatLog
	for rows.Next() {
		var i ChatLog
		if err := rows.Scan(
			&i.ID,
			&i.Session,
			&i.Question,
			&i.Answer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatLog = `-- name: UpdateChatLog :one
UPDATE chat_logs SET session = $2, question = $3, answer = $4
WHERE id = $1
RETURNING id, session, question, answer
`

type UpdateChatLogParams struct {
	ID       int32
	Session  json.RawMessage
	Question json.RawMessage
	Answer   json.RawMessage
}

func (q *Queries) UpdateChatLog(ctx context.Context, arg UpdateChatLogParams) (ChatLog, error) {
	row := q.db.QueryRowContext(ctx, updateChatLog,
		arg.ID,
		arg.Session,
		arg.Question,
		arg.Answer,
	)
	var i ChatLog
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.Question,
		&i.Answer,
	)
	return i, err
}
