// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_request.sql

package sqlc_queries

import (
	"context"
	"encoding/json"
	"time"
)

const claimChatRequest = `-- name: ClaimChatRequest :one
INSERT INTO chat_request (uuid, chat_session_uuid, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (chat_session_uuid, uuid) DO UPDATE
SET status = 'pending',
    error_code = '',
    attempt_count = chat_request.attempt_count + 1,
    updated_at = now()
WHERE chat_request.status IN ('failed', 'cancelled')
RETURNING id, uuid, chat_session_uuid, user_id, status, assistant_uuid, error_code, attempt_count, created_at, updated_at
`

type ClaimChatRequestParams struct {
	Uuid            string `json:"uuid"`
	ChatSessionUuid string `json:"chatSessionUuid"`
	UserID          int32  `json:"userId"`
}

func (q *Queries) ClaimChatRequest(ctx context.Context, arg ClaimChatRequestParams) (ChatRequest, error) {
	row := q.db.QueryRowContext(ctx, claimChatRequest, arg.Uuid, arg.ChatSessionUuid, arg.UserID)
	var i ChatRequest
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ChatSessionUuid,
		&i.UserID,
		&i.Status,
		&i.AssistantUuid,
		&i.ErrorCode,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeChatRequestWithMessage = `-- name: CompleteChatRequestWithMessage :one
WITH saved_message AS (
    INSERT INTO chat_message (
        chat_session_uuid, uuid, role, content, reasoning_content, model,
        token_count, score, user_id, created_by, updated_by, llm_summary,
        raw, artifacts, suggested_questions
    )
    VALUES (
        $1, $2, 'assistant',
        $3, $4, $5,
        $6, $7, $8,
        $9, $10, $11,
        $12, $13, $14
    )
    ON CONFLICT (chat_session_uuid, uuid) WHERE is_deleted = false DO UPDATE
    SET uuid = EXCLUDED.uuid
    RETURNING id, uuid, chat_session_uuid, role, content, reasoning_content, model, llm_summary, score, user_id, created_at, updated_at, created_by, updated_by, is_deleted, is_pin, token_count, raw, artifacts, suggested_questions
),
completed_request AS (
    UPDATE chat_request
    SET status = 'completed',
        assistant_uuid = (SELECT saved_message.uuid FROM saved_message),
        error_code = '',
        updated_at = now()
    WHERE chat_request.uuid = $15
      AND chat_request.chat_session_uuid = $1
      AND chat_request.user_id = $8
      AND chat_request.status IN ('pending', 'streaming')
    RETURNING id
)
SELECT saved_message.id, saved_message.uuid, saved_message.chat_session_uuid, saved_message.role, saved_message.content, saved_message.reasoning_content, saved_message.model, saved_message.llm_summary, saved_message.score, saved_message.user_id, saved_message.created_at, saved_message.updated_at, saved_message.created_by, saved_message.updated_by, saved_message.is_deleted, saved_message.is_pin, saved_message.token_count, saved_message.raw, saved_message.artifacts, saved_message.suggested_questions
FROM saved_message
JOIN completed_request ON true
`

type CompleteChatRequestWithMessageParams struct {
	ChatSessionUuid    string          `json:"chatSessionUuid"`
	MessageUuid        string          `json:"messageUuid"`
	Content            string          `json:"content"`
	ReasoningContent   string          `json:"reasoningContent"`
	Model              string          `json:"model"`
	TokenCount         int32           `json:"tokenCount"`
	Score              float64         `json:"score"`
	UserID             int32           `json:"userId"`
	CreatedBy          int32           `json:"createdBy"`
	UpdatedBy          int32           `json:"updatedBy"`
	LlmSummary         string          `json:"llmSummary"`
	Raw                json.RawMessage `json:"raw"`
	Artifacts          json.RawMessage `json:"artifacts"`
	SuggestedQuestions json.RawMessage `json:"suggestedQuestions"`
	RequestUuid        string          `json:"requestUuid"`
}

type CompleteChatRequestWithMessageRow struct {
	ID                 int32           `json:"id"`
	Uuid               string          `json:"uuid"`
	ChatSessionUuid    string          `json:"chatSessionUuid"`
	Role               string          `json:"role"`
	Content            string          `json:"content"`
	ReasoningContent   string          `json:"reasoningContent"`
	Model              string          `json:"model"`
	LlmSummary         string          `json:"llmSummary"`
	Score              float64         `json:"score"`
	UserID             int32           `json:"userId"`
	CreatedAt          time.Time       `json:"createdAt"`
	UpdatedAt          time.Time       `json:"updatedAt"`
	CreatedBy          int32           `json:"createdBy"`
	UpdatedBy          int32           `json:"updatedBy"`
	IsDeleted          bool            `json:"isDeleted"`
	IsPin              bool            `json:"isPin"`
	TokenCount         int32           `json:"tokenCount"`
	Raw                json.RawMessage `json:"raw"`
	Artifacts          json.RawMessage `json:"artifacts"`
	SuggestedQuestions json.RawMessage `json:"suggestedQuestions"`
}

func (q *Queries) CompleteChatRequestWithMessage(ctx context.Context, arg CompleteChatRequestWithMessageParams) (CompleteChatRequestWithMessageRow, error) {
	row := q.db.QueryRowContext(ctx, completeChatRequestWithMessage,
		arg.ChatSessionUuid,
		arg.MessageUuid,
		arg.Content,
		arg.ReasoningContent,
		arg.Model,
		arg.TokenCount,
		arg.Score,
		arg.UserID,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.LlmSummary,
		arg.Raw,
		arg.Artifacts,
		arg.SuggestedQuestions,
		arg.RequestUuid,
	)
	var i CompleteChatRequestWithMessageRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ChatSessionUuid,
		&i.Role,
		&i.Content,
		&i.ReasoningContent,
		&i.Model,
		&i.LlmSummary,
		&i.Score,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDeleted,
		&i.IsPin,
		&i.TokenCount,
		&i.Raw,
		&i.Artifacts,
		&i.SuggestedQuestions,
	)
	return i, err
}

const getChatRequest = `-- name: GetChatRequest :one
SELECT id, uuid, chat_session_uuid, user_id, status, assistant_uuid, error_code, attempt_count, created_at, updated_at
FROM chat_request
WHERE uuid = $1
  AND chat_session_uuid = $2
  AND user_id = $3
`

type GetChatRequestParams struct {
	Uuid            string `json:"uuid"`
	ChatSessionUuid string `json:"chatSessionUuid"`
	UserID          int32  `json:"userId"`
}

func (q *Queries) GetChatRequest(ctx context.Context, arg GetChatRequestParams) (ChatRequest, error) {
	row := q.db.QueryRowContext(ctx, getChatRequest, arg.Uuid, arg.ChatSessionUuid, arg.UserID)
	var i ChatRequest
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ChatSessionUuid,
		&i.UserID,
		&i.Status,
		&i.AssistantUuid,
		&i.ErrorCode,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markChatRequestFailed = `-- name: MarkChatRequestFailed :exec
UPDATE chat_request
SET status = 'failed', error_code = $4, updated_at = now()
WHERE uuid = $1
  AND chat_session_uuid = $2
  AND user_id = $3
  AND status <> 'completed'
`

type MarkChatRequestFailedParams struct {
	Uuid            string `json:"uuid"`
	ChatSessionUuid string `json:"chatSessionUuid"`
	UserID          int32  `json:"userId"`
	ErrorCode       string `json:"errorCode"`
}

func (q *Queries) MarkChatRequestFailed(ctx context.Context, arg MarkChatRequestFailedParams) error {
	_, err := q.db.ExecContext(ctx, markChatRequestFailed,
		arg.Uuid,
		arg.ChatSessionUuid,
		arg.UserID,
		arg.ErrorCode,
	)
	return err
}

const markChatRequestStreaming = `-- name: MarkChatRequestStreaming :exec
UPDATE chat_request
SET status = 'streaming', updated_at = now()
WHERE uuid = $1
  AND chat_session_uuid = $2
  AND user_id = $3
  AND status = 'pending'
`

type MarkChatRequestStreamingParams struct {
	Uuid            string `json:"uuid"`
	ChatSessionUuid string `json:"chatSessionUuid"`
	UserID          int32  `json:"userId"`
}

func (q *Queries) MarkChatRequestStreaming(ctx context.Context, arg MarkChatRequestStreamingParams) error {
	_, err := q.db.ExecContext(ctx, markChatRequestStreaming, arg.Uuid, arg.ChatSessionUuid, arg.UserID)
	return err
}
