// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: chat_api.sql

package sqlc_queries

import (
	"context"
)

const chatAPIByID = `-- name: ChatAPIByID :one
SELECT id, name, label, is_default, url, api_auth_header, api_auth_key FROM chat_api WHERE id = $1
`

func (q *Queries) ChatAPIByID(ctx context.Context, id int32) (ChatApi, error) {
	row := q.db.QueryRowContext(ctx, chatAPIByID, id)
	var i ChatApi
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.IsDefault,
		&i.Url,
		&i.ApiAuthHeader,
		&i.ApiAuthKey,
	)
	return i, err
}

const createChatAPI = `-- name: CreateChatAPI :one
INSERT INTO chat_api (name, label, is_default, url, api_auth_header, api_auth_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, label, is_default, url, api_auth_header, api_auth_key
`

type CreateChatAPIParams struct {
	Name          string
	Label         string
	IsDefault     bool
	Url           string
	ApiAuthHeader string
	ApiAuthKey    string
}

func (q *Queries) CreateChatAPI(ctx context.Context, arg CreateChatAPIParams) (ChatApi, error) {
	row := q.db.QueryRowContext(ctx, createChatAPI,
		arg.Name,
		arg.Label,
		arg.IsDefault,
		arg.Url,
		arg.ApiAuthHeader,
		arg.ApiAuthKey,
	)
	var i ChatApi
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.IsDefault,
		&i.Url,
		&i.ApiAuthHeader,
		&i.ApiAuthKey,
	)
	return i, err
}

const deleteChatAPI = `-- name: DeleteChatAPI :exec
DELETE FROM chat_api WHERE id = $1
`

func (q *Queries) DeleteChatAPI(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteChatAPI, id)
	return err
}

const getDefaultChatAPI = `-- name: GetDefaultChatAPI :one
SELECT id, name, label, is_default, url, api_auth_header, api_auth_key FROM chat_api WHERE is_default = true
`

func (q *Queries) GetDefaultChatAPI(ctx context.Context) (ChatApi, error) {
	row := q.db.QueryRowContext(ctx, getDefaultChatAPI)
	var i ChatApi
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.IsDefault,
		&i.Url,
		&i.ApiAuthHeader,
		&i.ApiAuthKey,
	)
	return i, err
}

const listChatAPIs = `-- name: ListChatAPIs :many
SELECT id, name, label, is_default, url, api_auth_header, api_auth_key FROM chat_api ORDER BY id
`

func (q *Queries) ListChatAPIs(ctx context.Context) ([]ChatApi, error) {
	rows, err := q.db.QueryContext(ctx, listChatAPIs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatApi
	for rows.Next() {
		var i ChatApi
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Label,
			&i.IsDefault,
			&i.Url,
			&i.ApiAuthHeader,
			&i.ApiAuthKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatAPI = `-- name: UpdateChatAPI :one
UPDATE chat_api SET name = $2, label = $3, is_default = $4, url = $5, api_auth_header = $6, api_auth_key = $7
WHERE id = $1
RETURNING id, name, label, is_default, url, api_auth_header, api_auth_key
`

type UpdateChatAPIParams struct {
	ID            int32
	Name          string
	Label         string
	IsDefault     bool
	Url           string
	ApiAuthHeader string
	ApiAuthKey    string
}

func (q *Queries) UpdateChatAPI(ctx context.Context, arg UpdateChatAPIParams) (ChatApi, error) {
	row := q.db.QueryRowContext(ctx, updateChatAPI,
		arg.ID,
		arg.Name,
		arg.Label,
		arg.IsDefault,
		arg.Url,
		arg.ApiAuthHeader,
		arg.ApiAuthKey,
	)
	var i ChatApi
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.IsDefault,
		&i.Url,
		&i.ApiAuthHeader,
		&i.ApiAuthKey,
	)
	return i, err
}
