// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateway.sql

package sqlc_queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const completeGatewayRequest = `-- name: CompleteGatewayRequest :exec
UPDATE gateway_request
SET status = $2,
    prompt_tokens = $3,
    completion_tokens = $4,
    total_tokens = $5,
    latency_ms = $6,
    provider_request_id = $7,
    error_code = $8,
    response_bytes = $9,
    response_sha256 = $10,
    response_sample = $11,
    response_truncated = $12,
    response_classification = $13,
    completed_at = NOW()
WHERE id = $1
`

type CompleteGatewayRequestParams struct {
	ID                     int64           `json:"id"`
	Status                 string          `json:"status"`
	PromptTokens           int32           `json:"promptTokens"`
	CompletionTokens       int32           `json:"completionTokens"`
	TotalTokens            int32           `json:"totalTokens"`
	LatencyMs              int64           `json:"latencyMs"`
	ProviderRequestID      string          `json:"providerRequestId"`
	ErrorCode              string          `json:"errorCode"`
	ResponseBytes          int64           `json:"responseBytes"`
	ResponseSha256         string          `json:"responseSha256"`
	ResponseSample         []byte          `json:"responseSample"`
	ResponseTruncated      bool            `json:"responseTruncated"`
	ResponseClassification json.RawMessage `json:"responseClassification"`
}

func (q *Queries) CompleteGatewayRequest(ctx context.Context, arg CompleteGatewayRequestParams) error {
	_, err := q.db.ExecContext(ctx, completeGatewayRequest,
		arg.ID,
		arg.Status,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.LatencyMs,
		arg.ProviderRequestID,
		arg.ErrorCode,
		arg.ResponseBytes,
		arg.ResponseSha256,
		arg.ResponseSample,
		arg.ResponseTruncated,
		arg.ResponseClassification,
	)
	return err
}

const countRecentGatewayRequests = `-- name: CountRecentGatewayRequests :one
SELECT COUNT(*) FROM gateway_request
WHERE api_key_id = $1 AND created_at >= NOW() - INTERVAL '1 minute'
`

func (q *Queries) CountRecentGatewayRequests(ctx context.Context, apiKeyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentGatewayRequests, apiKeyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGatewayRequest = `-- name: CreateGatewayRequest :one
INSERT INTO gateway_request (
    request_uuid, api_key_id, user_id, chat_model_id, requested_model, provider, stream,
    request_bytes, request_sha256, request_sample, request_truncated,
    request_classification, retention_until
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, request_uuid, api_key_id, user_id, chat_model_id, requested_model, provider, status, stream, prompt_tokens, completion_tokens, total_tokens, latency_ms, provider_request_id, error_code, request_bytes, response_bytes, request_sha256, response_sha256, request_sample, response_sample, request_truncated, response_truncated, request_classification, response_classification, created_at, completed_at, retention_until
`

type CreateGatewayRequestParams struct {
	RequestUuid           uuid.UUID       `json:"requestUuid"`
	ApiKeyID              int64           `json:"apiKeyId"`
	UserID                int32           `json:"userId"`
	ChatModelID           sql.NullInt32   `json:"chatModelId"`
	RequestedModel        string          `json:"requestedModel"`
	Provider              string          `json:"provider"`
	Stream                bool            `json:"stream"`
	RequestBytes          int64           `json:"requestBytes"`
	RequestSha256         string          `json:"requestSha256"`
	RequestSample         []byte          `json:"requestSample"`
	RequestTruncated      bool            `json:"requestTruncated"`
	RequestClassification json.RawMessage `json:"requestClassification"`
	RetentionUntil        time.Time       `json:"retentionUntil"`
}

func (q *Queries) CreateGatewayRequest(ctx context.Context, arg CreateGatewayRequestParams) (GatewayRequest, error) {
	row := q.db.QueryRowContext(ctx, createGatewayRequest,
		arg.RequestUuid,
		arg.ApiKeyID,
		arg.UserID,
		arg.ChatModelID,
		arg.RequestedModel,
		arg.Provider,
		arg.Stream,
		arg.RequestBytes,
		arg.RequestSha256,
		arg.RequestSample,
		arg.RequestTruncated,
		arg.RequestClassification,
		arg.RetentionUntil,
	)
	var i GatewayRequest
	err := row.Scan(
		&i.ID,
		&i.RequestUuid,
		&i.ApiKeyID,
		&i.UserID,
		&i.ChatModelID,
		&i.RequestedModel,
		&i.Provider,
		&i.Status,
		&i.Stream,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.LatencyMs,
		&i.ProviderRequestID,
		&i.ErrorCode,
		&i.RequestBytes,
		&i.ResponseBytes,
		&i.RequestSha256,
		&i.ResponseSha256,
		&i.RequestSample,
		&i.ResponseSample,
		&i.RequestTruncated,
		&i.ResponseTruncated,
		&i.RequestClassification,
		&i.ResponseClassification,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.RetentionUntil,
	)
	return i, err
}

const createVirtualAPIKey = `-- name: CreateVirtualAPIKey :one
INSERT INTO virtual_api_key (user_id, name, key_prefix, key_hash, expires_at, requests_per_minute)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, key_prefix, key_hash, status, requests_per_minute, expires_at, last_used_at, created_at, revoked_at
`

type CreateVirtualAPIKeyParams struct {
	UserID            int32        `json:"userId"`
	Name              string       `json:"name"`
	KeyPrefix         string       `json:"keyPrefix"`
	KeyHash           string       `json:"keyHash"`
	ExpiresAt         sql.NullTime `json:"expiresAt"`
	RequestsPerMinute int32        `json:"requestsPerMinute"`
}

func (q *Queries) CreateVirtualAPIKey(ctx context.Context, arg CreateVirtualAPIKeyParams) (VirtualApiKey, error) {
	row := q.db.QueryRowContext(ctx, createVirtualAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.ExpiresAt,
		arg.RequestsPerMinute,
	)
	var i VirtualApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Status,
		&i.RequestsPerMinute,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const gatewayRequestByIDAndUser = `-- name: GatewayRequestByIDAndUser :one
SELECT id, request_uuid, api_key_id, user_id, chat_model_id, requested_model, provider, status, stream, prompt_tokens, completion_tokens, total_tokens, latency_ms, provider_request_id, error_code, request_bytes, response_bytes, request_sha256, response_sha256, request_sample, response_sample, request_truncated, response_truncated, request_classification, response_classification, created_at, completed_at, retention_until FROM gateway_request
WHERE id = $1 AND api_key_id = $2 AND user_id = $3
`

type GatewayRequestByIDAndUserParams struct {
	ID       int64 `json:"id"`
	ApiKeyID int64 `json:"apiKeyId"`
	UserID   int32 `json:"userId"`
}

func (q *Queries) GatewayRequestByIDAndUser(ctx context.Context, arg GatewayRequestByIDAndUserParams) (GatewayRequest, error) {
	row := q.db.QueryRowContext(ctx, gatewayRequestByIDAndUser, arg.ID, arg.ApiKeyID, arg.UserID)
	var i GatewayRequest
	err := row.Scan(
		&i.ID,
		&i.RequestUuid,
		&i.ApiKeyID,
		&i.UserID,
		&i.ChatModelID,
		&i.RequestedModel,
		&i.Provider,
		&i.Status,
		&i.Stream,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.LatencyMs,
		&i.ProviderRequestID,
		&i.ErrorCode,
		&i.RequestBytes,
		&i.ResponseBytes,
		&i.RequestSha256,
		&i.ResponseSha256,
		&i.RequestSample,
		&i.ResponseSample,
		&i.RequestTruncated,
		&i.ResponseTruncated,
		&i.RequestClassification,
		&i.ResponseClassification,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.RetentionUntil,
	)
	return i, err
}

const gatewayUsageByKey = `-- name: GatewayUsageByKey :many
SELECT
    requested_model,
    COUNT(*) AS request_count,
    COALESCE(SUM(prompt_tokens), 0)::BIGINT AS prompt_tokens,
    COALESCE(SUM(completion_tokens), 0)::BIGINT AS completion_tokens,
    COALESCE(SUM(total_tokens), 0)::BIGINT AS total_tokens,
    MAX(created_at) AS last_used_at
FROM gateway_request
WHERE api_key_id = $1 AND user_id = $2
GROUP BY requested_model
ORDER BY request_count DESC, requested_model
`

type GatewayUsageByKeyParams struct {
	ApiKeyID int64 `json:"apiKeyId"`
	UserID   int32 `json:"userId"`
}

type GatewayUsageByKeyRow struct {
	RequestedModel   string      `json:"requestedModel"`
	RequestCount     int64       `json:"requestCount"`
	PromptTokens     int64       `json:"promptTokens"`
	CompletionTokens int64       `json:"completionTokens"`
	TotalTokens      int64       `json:"totalTokens"`
	LastUsedAt       interface{} `json:"lastUsedAt"`
}

func (q *Queries) GatewayUsageByKey(ctx context.Context, arg GatewayUsageByKeyParams) ([]GatewayUsageByKeyRow, error) {
	rows, err := q.db.QueryContext(ctx, gatewayUsageByKey, arg.ApiKeyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayUsageByKeyRow
	for rows.Next() {
		var i GatewayUsageByKeyRow
		if err := rows.Scan(
			&i.RequestedModel,
			&i.RequestCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayModels = `-- name: ListGatewayModels :many
SELECT id, name, label, is_default, url, api_auth_header, api_auth_key, user_id, enable_per_mode_ratelimit, max_token, default_token, order_number, http_time_out, is_enable, api_type, is_title_model FROM chat_model
WHERE is_enable = true AND api_type = 'openai'
ORDER BY order_number, name
`

func (q *Queries) ListGatewayModels(ctx context.Context) ([]ChatModel, error) {
	rows, err := q.db.QueryContext(ctx, listGatewayModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatModel
	for rows.Next() {
		var i ChatModel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Label,
			&i.IsDefault,
			&i.Url,
			&i.ApiAuthHeader,
			&i.ApiAuthKey,
			&i.UserID,
			&i.EnablePerModeRatelimit,
			&i.MaxToken,
			&i.DefaultToken,
			&i.OrderNumber,
			&i.HttpTimeOut,
			&i.IsEnable,
			&i.ApiType,
			&i.IsTitleModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayRequestsByKey = `-- name: ListGatewayRequestsByKey :many
SELECT id, request_uuid, requested_model, provider, status, stream,
       prompt_tokens, completion_tokens, total_tokens, latency_ms,
       request_bytes, response_bytes, request_truncated, response_truncated,
       created_at, completed_at, retention_until, error_code
FROM gateway_request
WHERE api_key_id = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListGatewayRequestsByKeyParams struct {
	ApiKeyID int64 `json:"apiKeyId"`
	UserID   int32 `json:"userId"`
	Limit    int32 `json:"limit"`
}

type ListGatewayRequestsByKeyRow struct {
	ID                int64        `json:"id"`
	RequestUuid       uuid.UUID    `json:"requestUuid"`
	RequestedModel    string       `json:"requestedModel"`
	Provider          string       `json:"provider"`
	Status            string       `json:"status"`
	Stream            bool         `json:"stream"`
	PromptTokens      int32        `json:"promptTokens"`
	CompletionTokens  int32        `json:"completionTokens"`
	TotalTokens       int32        `json:"totalTokens"`
	LatencyMs         int64        `json:"latencyMs"`
	RequestBytes      int64        `json:"requestBytes"`
	ResponseBytes     int64        `json:"responseBytes"`
	RequestTruncated  bool         `json:"requestTruncated"`
	ResponseTruncated bool         `json:"responseTruncated"`
	CreatedAt         time.Time    `json:"createdAt"`
	CompletedAt       sql.NullTime `json:"completedAt"`
	RetentionUntil    time.Time    `json:"retentionUntil"`
	ErrorCode         string       `json:"errorCode"`
}

func (q *Queries) ListGatewayRequestsByKey(ctx context.Context, arg ListGatewayRequestsByKeyParams) ([]ListGatewayRequestsByKeyRow, error) {
	rows, err := q.db.QueryContext(ctx, listGatewayRequestsByKey, arg.ApiKeyID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGatewayRequestsByKeyRow
	for rows.Next() {
		var i ListGatewayRequestsByKeyRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestUuid,
			&i.RequestedModel,
			&i.Provider,
			&i.Status,
			&i.Stream,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.LatencyMs,
			&i.RequestBytes,
			&i.ResponseBytes,
			&i.RequestTruncated,
			&i.ResponseTruncated,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.RetentionUntil,
			&i.ErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVirtualAPIKeysByUser = `-- name: ListVirtualAPIKeysByUser :many
SELECT id, user_id, name, key_prefix, key_hash, status, requests_per_minute, expires_at, last_used_at, created_at, revoked_at FROM virtual_api_key
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVirtualAPIKeysByUser(ctx context.Context, userID int32) ([]VirtualApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listVirtualAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VirtualApiKey
	for rows.Next() {
		var i VirtualApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Status,
			&i.RequestsPerMinute,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredGatewaySamples = `-- name: PurgeExpiredGatewaySamples :execrows
UPDATE gateway_request
SET request_sample = ''::BYTEA, response_sample = ''::BYTEA
WHERE retention_until <= NOW()
  AND (octet_length(request_sample) > 0 OR octet_length(response_sample) > 0)
`

func (q *Queries) PurgeExpiredGatewaySamples(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredGatewaySamples)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeVirtualAPIKey = `-- name: RevokeVirtualAPIKey :execrows
UPDATE virtual_api_key
SET status = 'revoked', revoked_at = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type RevokeVirtualAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"userId"`
}

func (q *Queries) RevokeVirtualAPIKey(ctx context.Context, arg RevokeVirtualAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeVirtualAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchVirtualAPIKey = `-- name: TouchVirtualAPIKey :exec
UPDATE virtual_api_key SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) TouchVirtualAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchVirtualAPIKey, id)
	return err
}

const virtualAPIKeyByHash = `-- name: VirtualAPIKeyByHash :one
SELECT id, user_id, name, key_prefix, key_hash, status, requests_per_minute, expires_at, last_used_at, created_at, revoked_at FROM virtual_api_key
WHERE key_hash = $1
`

func (q *Queries) VirtualAPIKeyByHash(ctx context.Context, keyHash string) (VirtualApiKey, error) {
	row := q.db.QueryRowContext(ctx, virtualAPIKeyByHash, keyHash)
	var i VirtualApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Status,
		&i.RequestsPerMinute,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const virtualAPIKeyByIDAndUser = `-- name: VirtualAPIKeyByIDAndUser :one
SELECT id, user_id, name, key_prefix, key_hash, status, requests_per_minute, expires_at, last_used_at, created_at, revoked_at FROM virtual_api_key
WHERE id = $1 AND user_id = $2
`

type VirtualAPIKeyByIDAndUserParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"userId"`
}

func (q *Queries) VirtualAPIKeyByIDAndUser(ctx context.Context, arg VirtualAPIKeyByIDAndUserParams) (VirtualApiKey, error) {
	row := q.db.QueryRowContext(ctx, virtualAPIKeyByIDAndUser, arg.ID, arg.UserID)
	var i VirtualApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Status,
		&i.RequestsPerMinute,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const virtualAdminAPIKeyByHash = `-- name: VirtualAdminAPIKeyByHash :one
SELECT vak.id, vak.user_id, vak.name, vak.key_prefix, vak.key_hash, vak.status, vak.requests_per_minute, vak.expires_at, vak.last_used_at, vak.created_at, vak.revoked_at
FROM virtual_api_key vak
JOIN auth_user au ON au.id = vak.user_id
WHERE vak.key_hash = $1
  AND au.is_superuser = true
  AND au.is_active = true
`

func (q *Queries) VirtualAdminAPIKeyByHash(ctx context.Context, keyHash string) (VirtualApiKey, error) {
	row := q.db.QueryRowContext(ctx, virtualAdminAPIKeyByHash, keyHash)
	var i VirtualApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Status,
		&i.RequestsPerMinute,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
