// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: jwt_secrets.sql

package sqlc_queries

import (
	"context"
)

const createJwtSecret = `-- name: CreateJwtSecret :one
INSERT INTO jwt_secrets (name, secret, audience)
VALUES ($1, $2, $3) RETURNING id, name, secret, audience
`

type CreateJwtSecretParams struct {
	Name     string
	Secret   string
	Audience string
}

func (q *Queries) CreateJwtSecret(ctx context.Context, arg CreateJwtSecretParams) (JwtSecret, error) {
	row := q.db.QueryRowContext(ctx, createJwtSecret, arg.Name, arg.Secret, arg.Audience)
	var i JwtSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.Audience,
	)
	return i, err
}

const getJwtSecret = `-- name: GetJwtSecret :one
SELECT id, name, secret, audience FROM jwt_secrets WHERE name = $1
`

func (q *Queries) GetJwtSecret(ctx context.Context, name string) (JwtSecret, error) {
	row := q.db.QueryRowContext(ctx, getJwtSecret, name)
	var i JwtSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.Audience,
	)
	return i, err
}
