// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_queries

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AuthUser struct {
	ID          int32     `json:"id"`
	Password    string    `json:"password"`
	LastLogin   time.Time `json:"lastLogin"`
	IsSuperuser bool      `json:"isSuperuser"`
	Username    string    `json:"username"`
	FirstName   string    `json:"firstName"`
	LastName    string    `json:"lastName"`
	Email       string    `json:"email"`
	IsStaff     bool      `json:"isStaff"`
	IsActive    bool      `json:"isActive"`
	DateJoined  time.Time `json:"dateJoined"`
}

type AuthUserManagement struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"userId"`
	RateLimit int32     `json:"rateLimit"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type BotAnswerHistory struct {
	ID         int32     `json:"id"`
	BotUuid    string    `json:"botUuid"`
	UserID     int32     `json:"userId"`
	Prompt     string    `json:"prompt"`
	Answer     string    `json:"answer"`
	Model      string    `json:"model"`
	TokensUsed int32     `json:"tokensUsed"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type ChatComment struct {
	ID              int32     `json:"id"`
	Uuid            string    `json:"uuid"`
	ChatSessionUuid string    `json:"chatSessionUuid"`
	ChatMessageUuid string    `json:"chatMessageUuid"`
	Content         string    `json:"content"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
	CreatedBy       int32     `json:"createdBy"`
	UpdatedBy       int32     `json:"updatedBy"`
}

type ChatFile struct {
	ID              int32     `json:"id"`
	Name            string    `json:"name"`
	Data            []byte    `json:"data"`
	CreatedAt       time.Time `json:"createdAt"`
	UserID          int32     `json:"userId"`
	ChatSessionUuid string    `json:"chatSessionUuid"`
	MimeType        string    `json:"mimeType"`
}

type ChatLog struct {
	ID        int32           `json:"id"`
	Session   json.RawMessage `json:"session"`
	Question  json.RawMessage `json:"question"`
	Answer    json.RawMessage `json:"answer"`
	CreatedAt time.Time       `json:"createdAt"`
}

type ChatMessage struct {
	ID                 int32           `json:"id"`
	Uuid               string          `json:"uuid"`
	ChatSessionUuid    string          `json:"chatSessionUuid"`
	Role               string          `json:"role"`
	Content            string          `json:"content"`
	ReasoningContent   string          `json:"reasoningContent"`
	Model              string          `json:"model"`
	LlmSummary         string          `json:"llmSummary"`
	Score              float64         `json:"score"`
	UserID             int32           `json:"userId"`
	CreatedAt          time.Time       `json:"createdAt"`
	UpdatedAt          time.Time       `json:"updatedAt"`
	CreatedBy          int32           `json:"createdBy"`
	UpdatedBy          int32           `json:"updatedBy"`
	IsDeleted          bool            `json:"isDeleted"`
	IsPin              bool            `json:"isPin"`
	TokenCount         int32           `json:"tokenCount"`
	Raw                json.RawMessage `json:"raw"`
	Artifacts          json.RawMessage `json:"artifacts"`
	SuggestedQuestions json.RawMessage `json:"suggestedQuestions"`
}

type ChatModel struct {
	ID                     int32  `json:"id"`
	Name                   string `json:"name"`
	Label                  string `json:"label"`
	IsDefault              bool   `json:"isDefault"`
	Url                    string `json:"url"`
	ApiAuthHeader          string `json:"apiAuthHeader"`
	ApiAuthKey             string `json:"apiAuthKey"`
	UserID                 int32  `json:"userId"`
	EnablePerModeRatelimit bool   `json:"enablePerModeRatelimit"`
	MaxToken               int32  `json:"maxToken"`
	DefaultToken           int32  `json:"defaultToken"`
	OrderNumber            int32  `json:"orderNumber"`
	HttpTimeOut            int32  `json:"httpTimeOut"`
	IsEnable               bool   `json:"isEnable"`
	ApiType                string `json:"apiType"`
}

type ChatPrompt struct {
	ID              int32     `json:"id"`
	Uuid            string    `json:"uuid"`
	ChatSessionUuid string    `json:"chatSessionUuid"`
	Role            string    `json:"role"`
	Content         string    `json:"content"`
	Score           float64   `json:"score"`
	UserID          int32     `json:"userId"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
	CreatedBy       int32     `json:"createdBy"`
	UpdatedBy       int32     `json:"updatedBy"`
	IsDeleted       bool      `json:"isDeleted"`
	TokenCount      int32     `json:"tokenCount"`
}

type ChatSession struct {
	ID                int32         `json:"id"`
	UserID            int32         `json:"userId"`
	Uuid              string        `json:"uuid"`
	Topic             string        `json:"topic"`
	CreatedAt         time.Time     `json:"createdAt"`
	UpdatedAt         time.Time     `json:"updatedAt"`
	Active            bool          `json:"active"`
	Model             string        `json:"model"`
	MaxLength         int32         `json:"maxLength"`
	Temperature       float64       `json:"temperature"`
	TopP              float64       `json:"topP"`
	MaxTokens         int32         `json:"maxTokens"`
	N                 int32         `json:"n"`
	SummarizeMode     bool          `json:"summarizeMode"`
	CodeRunnerEnabled bool          `json:"codeRunnerEnabled"`
	WorkspaceID       sql.NullInt32 `json:"workspaceId"`
	ArtifactEnabled   bool          `json:"artifactEnabled"`
	Debug             bool          `json:"debug"`
	ExploreMode       bool          `json:"exploreMode"`
}

type ChatSnapshot struct {
	ID           int32           `json:"id"`
	Typ          string          `json:"typ"`
	Uuid         string          `json:"uuid"`
	UserID       int32           `json:"userId"`
	Title        string          `json:"title"`
	Summary      string          `json:"summary"`
	Model        string          `json:"model"`
	Tags         json.RawMessage `json:"tags"`
	Session      json.RawMessage `json:"session"`
	Conversation json.RawMessage `json:"conversation"`
	CreatedAt    time.Time       `json:"createdAt"`
	Text         string          `json:"text"`
	SearchVector interface{}     `json:"searchVector"`
}

type ChatWorkspace struct {
	ID            int32     `json:"id"`
	Uuid          string    `json:"uuid"`
	UserID        int32     `json:"userId"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Color         string    `json:"color"`
	Icon          string    `json:"icon"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	IsDefault     bool      `json:"isDefault"`
	OrderPosition int32     `json:"orderPosition"`
}

type JwtSecret struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Secret   string `json:"secret"`
	Audience string `json:"audience"`
	Lifetime int16  `json:"lifetime"`
}

type UserActiveChatSession struct {
	ID              int32         `json:"id"`
	UserID          int32         `json:"userId"`
	ChatSessionUuid string        `json:"chatSessionUuid"`
	CreatedAt       time.Time     `json:"createdAt"`
	UpdatedAt       time.Time     `json:"updatedAt"`
	WorkspaceID     sql.NullInt32 `json:"workspaceId"`
}

type UserChatModelPrivilege struct {
	ID          int32     `json:"id"`
	UserID      int32     `json:"userId"`
	ChatModelID int32     `json:"chatModelId"`
	RateLimit   int32     `json:"rateLimit"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	CreatedBy   int32     `json:"createdBy"`
	UpdatedBy   int32     `json:"updatedBy"`
}
