// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc_queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID          int32            `json:"id"`
	Password    string           `json:"password"`
	LastLogin   pgtype.Timestamp `json:"lastLogin"`
	IsSuperuser bool             `json:"isSuperuser"`
	Username    string           `json:"username"`
	FirstName   string           `json:"firstName"`
	LastName    string           `json:"lastName"`
	Email       string           `json:"email"`
	IsStaff     bool             `json:"isStaff"`
	IsActive    bool             `json:"isActive"`
	DateJoined  pgtype.Timestamp `json:"dateJoined"`
}

type AuthUserManagement struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"userID"`
	RateLimit int32            `json:"rateLimit"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type ChatLog struct {
	ID        int32            `json:"id"`
	Session   []byte           `json:"session"`
	Question  []byte           `json:"question"`
	Answer    []byte           `json:"answer"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type ChatMessage struct {
	ID              int32            `json:"id"`
	Uuid            string           `json:"uuid"`
	ChatSessionUuid string           `json:"chatSessionUuid"`
	Role            string           `json:"role"`
	Content         string           `json:"content"`
	LlmSummary      string           `json:"llmSummary"`
	Score           float64          `json:"score"`
	UserID          int32            `json:"userID"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
	CreatedBy       int32            `json:"createdBy"`
	UpdatedBy       int32            `json:"updatedBy"`
	IsDeleted       bool             `json:"isDeleted"`
	IsPin           bool             `json:"isPin"`
	TokenCount      int32            `json:"tokenCount"`
	Raw             []byte           `json:"raw"`
}

type ChatModel struct {
	ID                     int32  `json:"id"`
	Name                   string `json:"name"`
	Label                  string `json:"label"`
	IsDefault              bool   `json:"isDefault"`
	Url                    string `json:"url"`
	ApiAuthHeader          string `json:"apiAuthHeader"`
	ApiAuthKey             string `json:"apiAuthKey"`
	UserID                 int32  `json:"userID"`
	EnablePerModeRatelimit bool   `json:"enablePerModeRatelimit"`
	MaxToken               int32  `json:"maxToken"`
	DefaultToken           int32  `json:"defaultToken"`
	OrderNumber            int32  `json:"orderNumber"`
	HttpTimeOut            int32  `json:"httpTimeOut"`
}

type ChatPrompt struct {
	ID              int32            `json:"id"`
	Uuid            string           `json:"uuid"`
	ChatSessionUuid string           `json:"chatSessionUuid"`
	Role            string           `json:"role"`
	Content         string           `json:"content"`
	Score           float64          `json:"score"`
	UserID          int32            `json:"userID"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
	CreatedBy       int32            `json:"createdBy"`
	UpdatedBy       int32            `json:"updatedBy"`
	IsDeleted       bool             `json:"isDeleted"`
	TokenCount      int32            `json:"tokenCount"`
}

type ChatSession struct {
	ID            int32            `json:"id"`
	UserID        int32            `json:"userID"`
	Uuid          string           `json:"uuid"`
	Topic         string           `json:"topic"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
	Active        bool             `json:"active"`
	Model         string           `json:"model"`
	MaxLength     int32            `json:"maxLength"`
	Temperature   float64          `json:"temperature"`
	TopP          float64          `json:"topP"`
	MaxTokens     int32            `json:"maxTokens"`
	N             int32            `json:"n"`
	SummarizeMode bool             `json:"summarizeMode"`
	Debug         bool             `json:"debug"`
}

type ChatSnapshot struct {
	ID           int32            `json:"id"`
	Uuid         string           `json:"uuid"`
	UserID       int32            `json:"userID"`
	Title        string           `json:"title"`
	Summary      string           `json:"summary"`
	Model        string           `json:"model"`
	Tags         []byte           `json:"tags"`
	Session      []byte           `json:"session"`
	Conversation []byte           `json:"conversation"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	Text         string           `json:"text"`
	SearchVector interface{}      `json:"searchVector"`
}

type JwtSecret struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Secret   string `json:"secret"`
	Audience string `json:"audience"`
	Lifetime int16  `json:"lifetime"`
}

type UserActiveChatSession struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"userID"`
	ChatSessionUuid string           `json:"chatSessionUuid"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
}

type UserChatModelPrivilege struct {
	ID          int32            `json:"id"`
	UserID      int32            `json:"userID"`
	ChatModelID int32            `json:"chatModelID"`
	RateLimit   int32            `json:"rateLimit"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
	CreatedBy   int32            `json:"createdBy"`
	UpdatedBy   int32            `json:"updatedBy"`
}
