.DEFAULT_GOAL:=test


export OPENAI_API_KEY=sk-KltHM7dsS8x2oL0KGJ69T3XXXX
export PG_HOST=192.168.0.135
export PG_DB=hwu
export PG_USER=hwu
export PG_PASS=using555
export PG_PORT=5432
 
test:
	@echo "Starting server..."
	echo $(OPENAI_API_KEY)
	echo $(PG_HOST)
	npx playwright test
       


